### ISSUE TITLE
Tan01 uses sin instead of tan on accident

### ISSUE THREAD

**Issue by coyo-t** [FoxyOfJungle/TurboGML#3]
https://github.com/FoxyOfJungle/TurboGML/blob/54e7db8a3b60d795ea742bc9b2355a541a124fa2/scripts/__tgm_core/__tgm_core.gml#L110-L113

**Comment by FoxyOfJungle** [comment]
Oh wow! Thank you for letting me know! I'll fix it. :D

Cheers!
